[package]
name = "rocal"
version = "0.1.0"
edition = "2021"

[dependencies]
rocal-macro = "0.1.0"
rocal-core = "0.1.0"
rocal-cli = "0.1.0"

[lib]
name = "rocal"
path = "src/lib.rs"

[[bin]]
name = "rocal"
path = "src/main.rs"
